# coding: utf-8

"""
    Kubeflow Pipelines on Tekton API

    This file contains REST API specification for Kubeflow Pipelines on Tekton. The file is autogenerated from the swagger definition.

    Contact: tommy.chaoping.li@ibm.com
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "kfp-tekton-server-api"
VERSION = "1.8.0rc4"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="Kubeflow Pipelines on Tekton API",
    author="kfp-tekton",
    author_email="tommy.chaoping.li@ibm.com",
    url="https://github.com/kubeflow/kfp-tekton",
    keywords=["OpenAPI", "OpenAPI-Generator", "Kubeflow Pipelines on Tekton API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="Apache 2.0",
    long_description="""\
    This file contains REST API specification for Kubeflow Pipelines on Tekton. The file is autogenerated from the swagger definition.  # noqa: E501
    """
)
