// Copyright 2023 kubeflow.org
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kubeflow/kfp-tekton/tekton-catalog/tekton-kfptask/pkg/apis/kfptask/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// KfpTaskLister helps list KfpTasks.
// All objects returned here must be treated as read-only.
type KfpTaskLister interface {
	// List lists all KfpTasks in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.KfpTask, err error)
	// KfpTasks returns an object that can list and get KfpTasks.
	KfpTasks(namespace string) KfpTaskNamespaceLister
	KfpTaskListerExpansion
}

// kfpTaskLister implements the KfpTaskLister interface.
type kfpTaskLister struct {
	indexer cache.Indexer
}

// NewKfpTaskLister returns a new KfpTaskLister.
func NewKfpTaskLister(indexer cache.Indexer) KfpTaskLister {
	return &kfpTaskLister{indexer: indexer}
}

// List lists all KfpTasks in the indexer.
func (s *kfpTaskLister) List(selector labels.Selector) (ret []*v1alpha1.KfpTask, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.KfpTask))
	})
	return ret, err
}

// KfpTasks returns an object that can list and get KfpTasks.
func (s *kfpTaskLister) KfpTasks(namespace string) KfpTaskNamespaceLister {
	return kfpTaskNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// KfpTaskNamespaceLister helps list and get KfpTasks.
// All objects returned here must be treated as read-only.
type KfpTaskNamespaceLister interface {
	// List lists all KfpTasks in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.KfpTask, err error)
	// Get retrieves the KfpTask from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.KfpTask, error)
	KfpTaskNamespaceListerExpansion
}

// kfpTaskNamespaceLister implements the KfpTaskNamespaceLister
// interface.
type kfpTaskNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all KfpTasks in the indexer for a given namespace.
func (s kfpTaskNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.KfpTask, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.KfpTask))
	})
	return ret, err
}

// Get retrieves the KfpTask from the indexer for a given namespace and name.
func (s kfpTaskNamespaceLister) Get(name string) (*v1alpha1.KfpTask, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("kfptask"), name)
	}
	return obj.(*v1alpha1.KfpTask), nil
}
