// Code generated by go-swagger; DO NOT EDIT.

package pipeline_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kubeflow/pipelines/backend/api/v1/go_http_client/pipeline_model"
)

// PipelineServiceUpdatePipelineDefaultVersionReader is a Reader for the PipelineServiceUpdatePipelineDefaultVersion structure.
type PipelineServiceUpdatePipelineDefaultVersionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PipelineServiceUpdatePipelineDefaultVersionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPipelineServiceUpdatePipelineDefaultVersionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPipelineServiceUpdatePipelineDefaultVersionDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPipelineServiceUpdatePipelineDefaultVersionOK creates a PipelineServiceUpdatePipelineDefaultVersionOK with default headers values
func NewPipelineServiceUpdatePipelineDefaultVersionOK() *PipelineServiceUpdatePipelineDefaultVersionOK {
	return &PipelineServiceUpdatePipelineDefaultVersionOK{}
}

/*
PipelineServiceUpdatePipelineDefaultVersionOK describes a response with status code 200, with default header values.

A successful response.
*/
type PipelineServiceUpdatePipelineDefaultVersionOK struct {
	Payload interface{}
}

// IsSuccess returns true when this pipeline service update pipeline default version o k response has a 2xx status code
func (o *PipelineServiceUpdatePipelineDefaultVersionOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this pipeline service update pipeline default version o k response has a 3xx status code
func (o *PipelineServiceUpdatePipelineDefaultVersionOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pipeline service update pipeline default version o k response has a 4xx status code
func (o *PipelineServiceUpdatePipelineDefaultVersionOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this pipeline service update pipeline default version o k response has a 5xx status code
func (o *PipelineServiceUpdatePipelineDefaultVersionOK) IsServerError() bool {
	return false
}

// IsCode returns true when this pipeline service update pipeline default version o k response a status code equal to that given
func (o *PipelineServiceUpdatePipelineDefaultVersionOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the pipeline service update pipeline default version o k response
func (o *PipelineServiceUpdatePipelineDefaultVersionOK) Code() int {
	return 200
}

func (o *PipelineServiceUpdatePipelineDefaultVersionOK) Error() string {
	return fmt.Sprintf("[POST /apis/v1/pipelines/{pipelineId}/default_version/{versionId}][%d] pipelineServiceUpdatePipelineDefaultVersionOK  %+v", 200, o.Payload)
}

func (o *PipelineServiceUpdatePipelineDefaultVersionOK) String() string {
	return fmt.Sprintf("[POST /apis/v1/pipelines/{pipelineId}/default_version/{versionId}][%d] pipelineServiceUpdatePipelineDefaultVersionOK  %+v", 200, o.Payload)
}

func (o *PipelineServiceUpdatePipelineDefaultVersionOK) GetPayload() interface{} {
	return o.Payload
}

func (o *PipelineServiceUpdatePipelineDefaultVersionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPipelineServiceUpdatePipelineDefaultVersionDefault creates a PipelineServiceUpdatePipelineDefaultVersionDefault with default headers values
func NewPipelineServiceUpdatePipelineDefaultVersionDefault(code int) *PipelineServiceUpdatePipelineDefaultVersionDefault {
	return &PipelineServiceUpdatePipelineDefaultVersionDefault{
		_statusCode: code,
	}
}

/*
PipelineServiceUpdatePipelineDefaultVersionDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type PipelineServiceUpdatePipelineDefaultVersionDefault struct {
	_statusCode int

	Payload *pipeline_model.GooglerpcStatus
}

// IsSuccess returns true when this pipeline service update pipeline default version default response has a 2xx status code
func (o *PipelineServiceUpdatePipelineDefaultVersionDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this pipeline service update pipeline default version default response has a 3xx status code
func (o *PipelineServiceUpdatePipelineDefaultVersionDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this pipeline service update pipeline default version default response has a 4xx status code
func (o *PipelineServiceUpdatePipelineDefaultVersionDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this pipeline service update pipeline default version default response has a 5xx status code
func (o *PipelineServiceUpdatePipelineDefaultVersionDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this pipeline service update pipeline default version default response a status code equal to that given
func (o *PipelineServiceUpdatePipelineDefaultVersionDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the pipeline service update pipeline default version default response
func (o *PipelineServiceUpdatePipelineDefaultVersionDefault) Code() int {
	return o._statusCode
}

func (o *PipelineServiceUpdatePipelineDefaultVersionDefault) Error() string {
	return fmt.Sprintf("[POST /apis/v1/pipelines/{pipelineId}/default_version/{versionId}][%d] PipelineService_UpdatePipelineDefaultVersion default  %+v", o._statusCode, o.Payload)
}

func (o *PipelineServiceUpdatePipelineDefaultVersionDefault) String() string {
	return fmt.Sprintf("[POST /apis/v1/pipelines/{pipelineId}/default_version/{versionId}][%d] PipelineService_UpdatePipelineDefaultVersion default  %+v", o._statusCode, o.Payload)
}

func (o *PipelineServiceUpdatePipelineDefaultVersionDefault) GetPayload() *pipeline_model.GooglerpcStatus {
	return o.Payload
}

func (o *PipelineServiceUpdatePipelineDefaultVersionDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(pipeline_model.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
