apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gcs-download
spec:
  params:
  - name: url1
  results:
  - description: /tmp/results.txt
    name: data
  steps:
  - args:
    - gsutil cat $0 | tee $1
    - $(inputs.params.url1)
    - $(results.data.path)
    command:
    - sh
    - -c
    image: google/cloud-sdk:279.0.0
    name: gcs-download
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gcs-download-2
spec:
  params:
  - name: url2
  results:
  - description: /tmp/results.txt
    name: data
  steps:
  - args:
    - gsutil cat $0 | tee $1
    - $(inputs.params.url2)
    - $(results.data.path)
    command:
    - sh
    - -c
    image: google/cloud-sdk:279.0.0
    name: gcs-download-2
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo
spec:
  params:
  - name: gcs-download-2-data
  - name: gcs-download-data
  steps:
  - args:
    - 'echo "Text 1: $0"; echo "Text 2: $1"'
    - $(inputs.params.gcs-download-data)
    - $(inputs.params.gcs-download-2-data)
    command:
    - sh
    - -c
    image: library/bash:4.4.23
    name: echo
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    pipelines.kubeflow.org/pipeline_spec: '{"description": "Download two messages
      in parallel and prints the concatenated result.", "inputs": [{"default": "gs://ml-pipeline-playground/shakespeare1.txt",
      "name": "url1", "optional": true}, {"default": "gs://ml-pipeline-playground/shakespeare2.txt",
      "name": "url2", "optional": true}], "name": "Parallel pipeline"}'
  name: parallel-pipeline
spec:
  params:
  - default: gs://ml-pipeline-playground/shakespeare1.txt
    name: url1
  - default: gs://ml-pipeline-playground/shakespeare2.txt
    name: url2
  tasks:
  - name: gcs-download
    params:
    - name: url1
      value: $(params.url1)
    taskRef:
      name: gcs-download
  - name: gcs-download-2
    params:
    - name: url2
      value: $(params.url2)
    taskRef:
      name: gcs-download-2
  - name: echo
    params:
    - name: gcs-download-2-data
      value: $(tasks.gcs-download-2.results.data)
    - name: gcs-download-data
      value: $(tasks.gcs-download.results.data)
    taskRef:
      name: echo
