diff a/backend/Dockerfile.scheduledworkflow b/backend/Dockerfile.scheduledworkflow	(rejected hunks)
@@ -8,13 +22,21 @@ RUN apk update && apk upgrade && \
     apk add --no-cache bash git openssh gcc musl-dev
 
 RUN GO111MODULE=on go build -o /bin/controller backend/src/crd/controller/scheduledworkflow/*.go
+# Check licenses and comply with license terms.
+RUN ./hack/install-go-licenses.sh
+RUN go-licenses csv /bin/controller > /tmp/licenses.csv && \
+    diff /tmp/licenses.csv backend/third_party_licenses/swf.csv && \
+    go-licenses save /tmp/licenses.csv --save_path /tmp/NOTICES
 
 FROM alpine:3.8
 WORKDIR /bin
 
 COPY --from=builder /bin/controller /bin/controller
-COPY --from=builder /go/src/github.com/kubeflow/pipelines/third_party/license.txt /bin/license.txt
+# Copy licenses and notices.
+COPY --from=builder /tmp/licenses.csv /third_party/licenses.csv
+COPY --from=builder /tmp/NOTICES /third_party/NOTICES
 RUN chmod +x /bin/controller
+RUN apk --no-cache add tzdata
 
 ENV NAMESPACE ""
 
