diff a/backend/Dockerfile.persistenceagent b/backend/Dockerfile.persistenceagent	(rejected hunks)
@@ -1,3 +1,17 @@
+# Copyright 2021 The Kubeflow Authors
+#
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+#      http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+
 FROM golang:1.13.15-alpine3.12 as builder
 
 WORKDIR /go/src/github.com/kubeflow/pipelines
@@ -8,12 +22,19 @@ RUN apk update && apk upgrade && \
     apk add --no-cache bash git openssh gcc musl-dev
 
 RUN GO111MODULE=on go build -o /bin/persistence_agent backend/src/agent/persistence/*.go
+# Check licenses and comply with license terms.
+RUN ./hack/install-go-licenses.sh
+RUN go-licenses csv /bin/persistence_agent > /tmp/licenses.csv && \
+    diff /tmp/licenses.csv backend/third_party_licenses/persistence_agent.csv && \
+    go-licenses save /tmp/licenses.csv --save_path /tmp/NOTICES
 
 FROM alpine:3.8
 WORKDIR /bin
 
 COPY --from=builder /bin/persistence_agent /bin/persistence_agent
-COPY --from=builder /go/src/github.com/kubeflow/pipelines/third_party/license.txt /bin/license.txt
+# Copy licenses and notices.
+COPY --from=builder /tmp/licenses.csv /third_party/licenses.csv
+COPY --from=builder /tmp/NOTICES /third_party/NOTICES
 
 ENV NAMESPACE ""
 
