// Code generated by go-swagger; DO NOT EDIT.

package run_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRunServiceReportRunMetricsParams creates a new RunServiceReportRunMetricsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRunServiceReportRunMetricsParams() *RunServiceReportRunMetricsParams {
	return &RunServiceReportRunMetricsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRunServiceReportRunMetricsParamsWithTimeout creates a new RunServiceReportRunMetricsParams object
// with the ability to set a timeout on a request.
func NewRunServiceReportRunMetricsParamsWithTimeout(timeout time.Duration) *RunServiceReportRunMetricsParams {
	return &RunServiceReportRunMetricsParams{
		timeout: timeout,
	}
}

// NewRunServiceReportRunMetricsParamsWithContext creates a new RunServiceReportRunMetricsParams object
// with the ability to set a context for a request.
func NewRunServiceReportRunMetricsParamsWithContext(ctx context.Context) *RunServiceReportRunMetricsParams {
	return &RunServiceReportRunMetricsParams{
		Context: ctx,
	}
}

// NewRunServiceReportRunMetricsParamsWithHTTPClient creates a new RunServiceReportRunMetricsParams object
// with the ability to set a custom HTTPClient for a request.
func NewRunServiceReportRunMetricsParamsWithHTTPClient(client *http.Client) *RunServiceReportRunMetricsParams {
	return &RunServiceReportRunMetricsParams{
		HTTPClient: client,
	}
}

/*
RunServiceReportRunMetricsParams contains all the parameters to send to the API endpoint

	for the run service report run metrics operation.

	Typically these are written to a http.Request.
*/
type RunServiceReportRunMetricsParams struct {

	// Body.
	Body RunServiceReportRunMetricsBody

	/* RunID.

	   Required. The parent run ID of the metric.
	*/
	RunID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the run service report run metrics params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RunServiceReportRunMetricsParams) WithDefaults() *RunServiceReportRunMetricsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the run service report run metrics params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RunServiceReportRunMetricsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the run service report run metrics params
func (o *RunServiceReportRunMetricsParams) WithTimeout(timeout time.Duration) *RunServiceReportRunMetricsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the run service report run metrics params
func (o *RunServiceReportRunMetricsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the run service report run metrics params
func (o *RunServiceReportRunMetricsParams) WithContext(ctx context.Context) *RunServiceReportRunMetricsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the run service report run metrics params
func (o *RunServiceReportRunMetricsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the run service report run metrics params
func (o *RunServiceReportRunMetricsParams) WithHTTPClient(client *http.Client) *RunServiceReportRunMetricsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the run service report run metrics params
func (o *RunServiceReportRunMetricsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the run service report run metrics params
func (o *RunServiceReportRunMetricsParams) WithBody(body RunServiceReportRunMetricsBody) *RunServiceReportRunMetricsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the run service report run metrics params
func (o *RunServiceReportRunMetricsParams) SetBody(body RunServiceReportRunMetricsBody) {
	o.Body = body
}

// WithRunID adds the runID to the run service report run metrics params
func (o *RunServiceReportRunMetricsParams) WithRunID(runID string) *RunServiceReportRunMetricsParams {
	o.SetRunID(runID)
	return o
}

// SetRunID adds the runId to the run service report run metrics params
func (o *RunServiceReportRunMetricsParams) SetRunID(runID string) {
	o.RunID = runID
}

// WriteToRequest writes these params to a swagger request
func (o *RunServiceReportRunMetricsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param runId
	if err := r.SetPathParam("runId", o.RunID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
