# Copyright 2023 kubeflow.org
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM golang:1.20.4-alpine3.17 as builder

WORKDIR /go/src/github.com/kubeflow/kfp-tekton/tekton-catalog/tekton-kfptask
COPY . .

# Needed musl-dev for github.com/mattn/go-sqlite3
RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh gcc musl-dev patch

RUN CGO_ENABLED=0 GO111MODULE=on go build -o /bin/controller ./cmd/controller/*.go

FROM alpine:3.17
WORKDIR /bin

COPY --from=builder /bin/controller /bin/controller
RUN chmod +x /bin/controller
RUN apk --no-cache add tzdata

CMD /bin/controller
