apiVersion: apps/v1
kind: Deployment
metadata:
  name: kfp-driver
  namespace: kubeflow
  labels:
    app.kubernetes.io/name: kfp-driver
    app.kubernetes.io/component: ckfp-driver
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: devel
    app.kubernetes.io/part-of: kubeflow-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kfp-driver
      app.kubernetes.io/component: kfp-driver
      app.kubernetes.io/instance: default
      app.kubernetes.io/part-of: kubeflow-pipeline
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      labels:
        app.kubernetes.io/name: kfp-driver
        app.kubernetes.io/component: kfp-driver
        app.kubernetes.io/instance: default
        app.kubernetes.io/version: devel
        app.kubernetes.io/part-of: kubeflow-pipeline
        app: kfp-driver
    spec:
      serviceAccountName: kfp-driver
      containers:
        - name: kfp-driver
          image: yihongwang/kfp-v2-dev-driver-controller:latest
          imagePullPolicy: Always
          env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
