// Code generated by go-swagger; DO NOT EDIT.

package visualization_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kubeflow/pipelines/backend/api/v1/go_http_client/visualization_model"
)

// VisualizationServiceCreateVisualizationReader is a Reader for the VisualizationServiceCreateVisualization structure.
type VisualizationServiceCreateVisualizationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VisualizationServiceCreateVisualizationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewVisualizationServiceCreateVisualizationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewVisualizationServiceCreateVisualizationDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewVisualizationServiceCreateVisualizationOK creates a VisualizationServiceCreateVisualizationOK with default headers values
func NewVisualizationServiceCreateVisualizationOK() *VisualizationServiceCreateVisualizationOK {
	return &VisualizationServiceCreateVisualizationOK{}
}

/*
VisualizationServiceCreateVisualizationOK describes a response with status code 200, with default header values.

A successful response.
*/
type VisualizationServiceCreateVisualizationOK struct {
	Payload *visualization_model.V1Visualization
}

// IsSuccess returns true when this visualization service create visualization o k response has a 2xx status code
func (o *VisualizationServiceCreateVisualizationOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this visualization service create visualization o k response has a 3xx status code
func (o *VisualizationServiceCreateVisualizationOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this visualization service create visualization o k response has a 4xx status code
func (o *VisualizationServiceCreateVisualizationOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this visualization service create visualization o k response has a 5xx status code
func (o *VisualizationServiceCreateVisualizationOK) IsServerError() bool {
	return false
}

// IsCode returns true when this visualization service create visualization o k response a status code equal to that given
func (o *VisualizationServiceCreateVisualizationOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the visualization service create visualization o k response
func (o *VisualizationServiceCreateVisualizationOK) Code() int {
	return 200
}

func (o *VisualizationServiceCreateVisualizationOK) Error() string {
	return fmt.Sprintf("[POST /apis/v1/visualizations/{namespace}][%d] visualizationServiceCreateVisualizationOK  %+v", 200, o.Payload)
}

func (o *VisualizationServiceCreateVisualizationOK) String() string {
	return fmt.Sprintf("[POST /apis/v1/visualizations/{namespace}][%d] visualizationServiceCreateVisualizationOK  %+v", 200, o.Payload)
}

func (o *VisualizationServiceCreateVisualizationOK) GetPayload() *visualization_model.V1Visualization {
	return o.Payload
}

func (o *VisualizationServiceCreateVisualizationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(visualization_model.V1Visualization)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewVisualizationServiceCreateVisualizationDefault creates a VisualizationServiceCreateVisualizationDefault with default headers values
func NewVisualizationServiceCreateVisualizationDefault(code int) *VisualizationServiceCreateVisualizationDefault {
	return &VisualizationServiceCreateVisualizationDefault{
		_statusCode: code,
	}
}

/*
VisualizationServiceCreateVisualizationDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type VisualizationServiceCreateVisualizationDefault struct {
	_statusCode int

	Payload *visualization_model.GooglerpcStatus
}

// IsSuccess returns true when this visualization service create visualization default response has a 2xx status code
func (o *VisualizationServiceCreateVisualizationDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this visualization service create visualization default response has a 3xx status code
func (o *VisualizationServiceCreateVisualizationDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this visualization service create visualization default response has a 4xx status code
func (o *VisualizationServiceCreateVisualizationDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this visualization service create visualization default response has a 5xx status code
func (o *VisualizationServiceCreateVisualizationDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this visualization service create visualization default response a status code equal to that given
func (o *VisualizationServiceCreateVisualizationDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the visualization service create visualization default response
func (o *VisualizationServiceCreateVisualizationDefault) Code() int {
	return o._statusCode
}

func (o *VisualizationServiceCreateVisualizationDefault) Error() string {
	return fmt.Sprintf("[POST /apis/v1/visualizations/{namespace}][%d] VisualizationService_CreateVisualization default  %+v", o._statusCode, o.Payload)
}

func (o *VisualizationServiceCreateVisualizationDefault) String() string {
	return fmt.Sprintf("[POST /apis/v1/visualizations/{namespace}][%d] VisualizationService_CreateVisualization default  %+v", o._statusCode, o.Payload)
}

func (o *VisualizationServiceCreateVisualizationDefault) GetPayload() *visualization_model.GooglerpcStatus {
	return o.Payload
}

func (o *VisualizationServiceCreateVisualizationDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(visualization_model.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
