// Code generated by go-swagger; DO NOT EDIT.

package visualization_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kubeflow/pipelines/backend/api/v1/go_http_client/visualization_model"
)

// NewVisualizationServiceCreateVisualizationParams creates a new VisualizationServiceCreateVisualizationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewVisualizationServiceCreateVisualizationParams() *VisualizationServiceCreateVisualizationParams {
	return &VisualizationServiceCreateVisualizationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewVisualizationServiceCreateVisualizationParamsWithTimeout creates a new VisualizationServiceCreateVisualizationParams object
// with the ability to set a timeout on a request.
func NewVisualizationServiceCreateVisualizationParamsWithTimeout(timeout time.Duration) *VisualizationServiceCreateVisualizationParams {
	return &VisualizationServiceCreateVisualizationParams{
		timeout: timeout,
	}
}

// NewVisualizationServiceCreateVisualizationParamsWithContext creates a new VisualizationServiceCreateVisualizationParams object
// with the ability to set a context for a request.
func NewVisualizationServiceCreateVisualizationParamsWithContext(ctx context.Context) *VisualizationServiceCreateVisualizationParams {
	return &VisualizationServiceCreateVisualizationParams{
		Context: ctx,
	}
}

// NewVisualizationServiceCreateVisualizationParamsWithHTTPClient creates a new VisualizationServiceCreateVisualizationParams object
// with the ability to set a custom HTTPClient for a request.
func NewVisualizationServiceCreateVisualizationParamsWithHTTPClient(client *http.Client) *VisualizationServiceCreateVisualizationParams {
	return &VisualizationServiceCreateVisualizationParams{
		HTTPClient: client,
	}
}

/*
VisualizationServiceCreateVisualizationParams contains all the parameters to send to the API endpoint

	for the visualization service create visualization operation.

	Typically these are written to a http.Request.
*/
type VisualizationServiceCreateVisualizationParams struct {

	// Namespace.
	Namespace string

	// Visualization.
	Visualization *visualization_model.V1Visualization

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the visualization service create visualization params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VisualizationServiceCreateVisualizationParams) WithDefaults() *VisualizationServiceCreateVisualizationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the visualization service create visualization params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VisualizationServiceCreateVisualizationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the visualization service create visualization params
func (o *VisualizationServiceCreateVisualizationParams) WithTimeout(timeout time.Duration) *VisualizationServiceCreateVisualizationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the visualization service create visualization params
func (o *VisualizationServiceCreateVisualizationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the visualization service create visualization params
func (o *VisualizationServiceCreateVisualizationParams) WithContext(ctx context.Context) *VisualizationServiceCreateVisualizationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the visualization service create visualization params
func (o *VisualizationServiceCreateVisualizationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the visualization service create visualization params
func (o *VisualizationServiceCreateVisualizationParams) WithHTTPClient(client *http.Client) *VisualizationServiceCreateVisualizationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the visualization service create visualization params
func (o *VisualizationServiceCreateVisualizationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNamespace adds the namespace to the visualization service create visualization params
func (o *VisualizationServiceCreateVisualizationParams) WithNamespace(namespace string) *VisualizationServiceCreateVisualizationParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the visualization service create visualization params
func (o *VisualizationServiceCreateVisualizationParams) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WithVisualization adds the visualization to the visualization service create visualization params
func (o *VisualizationServiceCreateVisualizationParams) WithVisualization(visualization *visualization_model.V1Visualization) *VisualizationServiceCreateVisualizationParams {
	o.SetVisualization(visualization)
	return o
}

// SetVisualization adds the visualization to the visualization service create visualization params
func (o *VisualizationServiceCreateVisualizationParams) SetVisualization(visualization *visualization_model.V1Visualization) {
	o.Visualization = visualization
}

// WriteToRequest writes these params to a swagger request
func (o *VisualizationServiceCreateVisualizationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param namespace
	if err := r.SetPathParam("namespace", o.Namespace); err != nil {
		return err
	}
	if o.Visualization != nil {
		if err := r.SetBodyParam(o.Visualization); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
