// Copyright 2023 kubeflow.org
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	kfptaskv1alpha1 "github.com/kubeflow/pipelines/backend/src/v2/tekton-kfptask/apis/kfptask/v1alpha1"
	versioned "github.com/kubeflow/pipelines/backend/src/v2/tekton-kfptask/client/clientset/versioned"
	internalinterfaces "github.com/kubeflow/pipelines/backend/src/v2/tekton-kfptask/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/kubeflow/pipelines/backend/src/v2/tekton-kfptask/client/listers/kfptask/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// KfpTaskInformer provides access to a shared informer and lister for
// KfpTasks.
type KfpTaskInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.KfpTaskLister
}

type kfpTaskInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewKfpTaskInformer constructs a new informer for KfpTask type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewKfpTaskInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredKfpTaskInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredKfpTaskInformer constructs a new informer for KfpTask type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredKfpTaskInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CustomV1alpha1().KfpTasks(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CustomV1alpha1().KfpTasks(namespace).Watch(context.TODO(), options)
			},
		},
		&kfptaskv1alpha1.KfpTask{},
		resyncPeriod,
		indexers,
	)
}

func (f *kfpTaskInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredKfpTaskInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *kfpTaskInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&kfptaskv1alpha1.KfpTask{}, f.defaultInformer)
}

func (f *kfpTaskInformer) Lister() v1alpha1.KfpTaskLister {
	return v1alpha1.NewKfpTaskLister(f.Informer().GetIndexer())
}
