// Code generated by go-swagger; DO NOT EDIT.

package job_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kubeflow/pipelines/backend/api/v1/go_http_client/job_model"
)

// JobServiceCreateJobReader is a Reader for the JobServiceCreateJob structure.
type JobServiceCreateJobReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *JobServiceCreateJobReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewJobServiceCreateJobOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewJobServiceCreateJobDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewJobServiceCreateJobOK creates a JobServiceCreateJobOK with default headers values
func NewJobServiceCreateJobOK() *JobServiceCreateJobOK {
	return &JobServiceCreateJobOK{}
}

/*
JobServiceCreateJobOK describes a response with status code 200, with default header values.

A successful response.
*/
type JobServiceCreateJobOK struct {
	Payload *job_model.V1Job
}

// IsSuccess returns true when this job service create job o k response has a 2xx status code
func (o *JobServiceCreateJobOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this job service create job o k response has a 3xx status code
func (o *JobServiceCreateJobOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this job service create job o k response has a 4xx status code
func (o *JobServiceCreateJobOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this job service create job o k response has a 5xx status code
func (o *JobServiceCreateJobOK) IsServerError() bool {
	return false
}

// IsCode returns true when this job service create job o k response a status code equal to that given
func (o *JobServiceCreateJobOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the job service create job o k response
func (o *JobServiceCreateJobOK) Code() int {
	return 200
}

func (o *JobServiceCreateJobOK) Error() string {
	return fmt.Sprintf("[POST /apis/v1/jobs][%d] jobServiceCreateJobOK  %+v", 200, o.Payload)
}

func (o *JobServiceCreateJobOK) String() string {
	return fmt.Sprintf("[POST /apis/v1/jobs][%d] jobServiceCreateJobOK  %+v", 200, o.Payload)
}

func (o *JobServiceCreateJobOK) GetPayload() *job_model.V1Job {
	return o.Payload
}

func (o *JobServiceCreateJobOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(job_model.V1Job)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewJobServiceCreateJobDefault creates a JobServiceCreateJobDefault with default headers values
func NewJobServiceCreateJobDefault(code int) *JobServiceCreateJobDefault {
	return &JobServiceCreateJobDefault{
		_statusCode: code,
	}
}

/*
JobServiceCreateJobDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type JobServiceCreateJobDefault struct {
	_statusCode int

	Payload *job_model.GooglerpcStatus
}

// IsSuccess returns true when this job service create job default response has a 2xx status code
func (o *JobServiceCreateJobDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this job service create job default response has a 3xx status code
func (o *JobServiceCreateJobDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this job service create job default response has a 4xx status code
func (o *JobServiceCreateJobDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this job service create job default response has a 5xx status code
func (o *JobServiceCreateJobDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this job service create job default response a status code equal to that given
func (o *JobServiceCreateJobDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the job service create job default response
func (o *JobServiceCreateJobDefault) Code() int {
	return o._statusCode
}

func (o *JobServiceCreateJobDefault) Error() string {
	return fmt.Sprintf("[POST /apis/v1/jobs][%d] JobService_CreateJob default  %+v", o._statusCode, o.Payload)
}

func (o *JobServiceCreateJobDefault) String() string {
	return fmt.Sprintf("[POST /apis/v1/jobs][%d] JobService_CreateJob default  %+v", o._statusCode, o.Payload)
}

func (o *JobServiceCreateJobDefault) GetPayload() *job_model.GooglerpcStatus {
	return o.Payload
}

func (o *JobServiceCreateJobDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(job_model.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
