apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: coin-bucket
spec:
  type: storage
  params:
  - name: type
    value: gcs
  - name: location
    value: s3://tektonstorage/coin/
  - name: dir
    value: "y"
  secrets:
    - fieldName: BOTO_CONFIG
      secretName: pipelines-cos-credentials
      secretKey: boto_config
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: random-bucket
spec:
  type: storage
  params:
  - name: type
    value: gcs
  - name: location
    value: s3://tektonstorage/random/
  - name: dir
    value: "y"
  secrets:
    - fieldName: BOTO_CONFIG
      secretName: pipelines-cos-credentials
      secretKey: boto_config
