apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: null
  name: kfp-dag-driver
spec:
  params:
  - name: kfp-task-spec
    type: string
  - default: ""
    name: kfp-parent-context-name
    type: string
  - name: kfp-execution-name
    type: string
  results:
  - description: execution id
    name: execution-id
  - description: context name
    name: context-name
  steps:
  - args:
    - --logtostderr
    - --driver_type=DAG
    - --mlmd_url=metadata-grpc-service.kubeflow.svc.cluster.local:8080
    - --parent_context_name=$(params.kfp-parent-context-name)
    - --execution_name=kfp-$(params.kfp-execution-name)
    - --output_path_execution_id=$(results.execution-id.path)
    - --output_path_context_name=$(results.context-name.path)
    - --task_spec=$(params.kfp-task-spec)
    command:
    - /bin/kfp-driver
    image: docker.io/yihongwang/kfp-driver-dev:0.8
    name: dag-driver-main
    resources: {}
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: null
  name: kfp-executor-driver
spec:
  params:
  - name: kfp-task-spec
    type: string
  - default: ""
    name: kfp-parent-context-name
    type: string
  - name: kfp-execution-name
    type: string
  - name: kfp-executor-spec
    type: string
  - name: kfp-executor-template-name
    type: string
  - name: kfp-executor-template-namespace
    type: string
  results:
  - description: execution id
    name: execution-id
  - description: pod spec patch
    name: pod-spec-patch
  steps:
  - args:
    - --logtostderr
    - --driver_type=EXECUTOR
    - --mlmd_url=metadata-grpc-service.kubeflow.svc.cluster.local:8080
    - --parent_context_name=$(params.kfp-parent-context-name)
    - --execution_name=kfp-$(params.kfp-execution-name)
    - --output_path_execution_id=$(results.execution-id.path)
    - --task_spec=$(params.kfp-task-spec)
    - --executor_spec=$(params.kfp-executor-spec)
    - --output_path_pod_spec_patch=$(results.pod-spec-patch.path)
    - --task_template_namespace=$(params.kfp-executor-template-namespace)
    - --task_template_name=$(params.kfp-executor-template-name)
    command:
    - /bin/kfp-driver
    image: docker.io/yihongwang/kfp-driver-dev:0.8
    name: executor-driver-main
    resources: {}
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: null
  labels:
    pipeline-uid: acc04d63-ea99-4c90-8645-5baf054dfa8c
  name: task-0-acc04d63-ea99-4c90-8645-5baf054dfa8c
spec:
  stepTemplate:
    name: ""
    resources: {}
    volumeMounts:
    - mountPath: /kfp/entrypoint
      name: data
  steps:
  - args:
    - /bin/kfp-entrypoint
    - /kfp/entrypoint/entrypoint
    command:
    - cp
    image: yihongwang/kfp-entrypoint-dev:0.8
    name: entrypoint-init
    resources: {}
  - command:
    - /bin/sh
    - -c
    image: dummy
    name: task-executor
    resources: {}
  volumes:
  - emptyDir: {}
    name: data
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: null
  labels:
    pipeline-uid: acc04d63-ea99-4c90-8645-5baf054dfa8c
  name: task-1-acc04d63-ea99-4c90-8645-5baf054dfa8c
spec:
  stepTemplate:
    name: ""
    resources: {}
    volumeMounts:
    - mountPath: /kfp/entrypoint
      name: data
  steps:
  - args:
    - /bin/kfp-entrypoint
    - /kfp/entrypoint/entrypoint
    command:
    - cp
    image: yihongwang/kfp-entrypoint-dev:0.8
    name: entrypoint-init
    resources: {}
  - command:
    - /bin/sh
    - -c
    image: dummy
    name: task-executor
    resources: {}
  volumes:
  - emptyDir: {}
    name: data
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  labels:
    pipeline-uid: acc04d63-ea99-4c90-8645-5baf054dfa8c
  name: pipelinerun-0-acc04d63-ea99-4c90-8645-5baf054dfa8c
spec:
  params:
  - name: kfp-task-spec
    value: '{"taskInfo":{"name":"hello-world-dag"},"inputs":{"parameters":{"text":{"runtimeValue":{"constantValue":{"stringValue":"Hello,
      World!"}}}}}}'
  pipelineSpec:
    params:
    - name: kfp-task-spec
      type: string
    tasks:
    - name: kfp-dag-root-main
      params:
      - name: kfp-execution-name
        value: root-dag-driver-$(context.pipelineRun.uid)
      - name: kfp-task-spec
        value: $(params.kfp-task-spec)
      taskRef:
        name: kfp-dag-driver
    - name: producer-executor-driver
      params:
      - name: kfp-execution-name
        value: producer-executor-driver-$(context.pipelineRun.uid)
      - name: kfp-parent-context-name
        value: $(tasks.kfp-dag-root-main.results.context-name)
      - name: kfp-executor-template-namespace
        value: $(context.pipelineRun.namespace)
      - name: kfp-executor-template-name
        value: task-0-acc04d63-ea99-4c90-8645-5baf054dfa8c
      - name: kfp-task-spec
        value: '{"taskInfo":{"name":"Producer"},"inputs":{"parameters":{"text":{"componentInputParameter":"text"}}},"outputs":{"parameters":{"output_value":{"type":"STRING"}}},"executorLabel":"Producer"}'
      - name: kfp-executor-spec
        value: '{"container":{"image":"google/cloud-sdk:latest","command":["sh","-c","set
          -e -x\necho \"$0, this is an output parameter\" | gsutil cp - \"$1\"\n","{{$.inputs.parameters[''text'']}}","{{$.outputs.parameters[''output_value''].output_file}}"]}}'
      runAfter:
      - kfp-dag-root-main
      taskRef:
        name: kfp-executor-driver
    - name: producer
      runAfter:
      - producer-executor-driver
      taskRef:
        name: task-0-acc04d63-ea99-4c90-8645-5baf054dfa8c
    - name: consumer-executor-driver
      params:
      - name: kfp-execution-name
        value: consumer-executor-driver-$(context.pipelineRun.uid)
      - name: kfp-parent-context-name
        value: $(tasks.kfp-dag-root-main.results.context-name)
      - name: kfp-executor-template-namespace
        value: $(context.pipelineRun.namespace)
      - name: kfp-executor-template-name
        value: task-1-acc04d63-ea99-4c90-8645-5baf054dfa8c
      - name: kfp-task-spec
        value: '{"taskInfo":{"name":"Consumer"},"inputs":{"parameters":{"input_value":{"taskOutputParameter":{"producerTask":"Producer","outputParameterKey":"output_value"}}}},"executorLabel":"Consumer"}'
      - name: kfp-executor-spec
        value: '{"container":{"image":"google/cloud-sdk:latest","command":["sh","-c","set
          -e -x\necho \"Read from an input parameter: \" \u0026\u0026 echo \"$0\"\n","{{$.inputs.parameters[''input_value'']}}"]}}'
      runAfter:
      - producer
      taskRef:
        name: kfp-executor-driver
    - name: consumer
      runAfter:
      - consumer-executor-driver
      taskRef:
        name: task-1-acc04d63-ea99-4c90-8645-5baf054dfa8c
  serviceAccountNames:
  - serviceAccountName: kfp-tekton
    taskName: producer-executor-driver
  - serviceAccountName: kfp-tekton
    taskName: consumer-executor-driver
status: {}

