// Code generated by go-swagger; DO NOT EDIT.

package pipeline_upload_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kubeflow/pipelines/backend/api/v1/go_http_client/pipeline_upload_model"
)

// PipelineServiceUploadPipelineReader is a Reader for the PipelineServiceUploadPipeline structure.
type PipelineServiceUploadPipelineReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PipelineServiceUploadPipelineReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPipelineServiceUploadPipelineOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPipelineServiceUploadPipelineDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPipelineServiceUploadPipelineOK creates a PipelineServiceUploadPipelineOK with default headers values
func NewPipelineServiceUploadPipelineOK() *PipelineServiceUploadPipelineOK {
	return &PipelineServiceUploadPipelineOK{}
}

/*
PipelineServiceUploadPipelineOK describes a response with status code 200, with default header values.

PipelineServiceUploadPipelineOK pipeline service upload pipeline o k
*/
type PipelineServiceUploadPipelineOK struct {
	Payload *pipeline_upload_model.V1Pipeline
}

// IsSuccess returns true when this pipeline service upload pipeline o k response has a 2xx status code
func (o *PipelineServiceUploadPipelineOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this pipeline service upload pipeline o k response has a 3xx status code
func (o *PipelineServiceUploadPipelineOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pipeline service upload pipeline o k response has a 4xx status code
func (o *PipelineServiceUploadPipelineOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this pipeline service upload pipeline o k response has a 5xx status code
func (o *PipelineServiceUploadPipelineOK) IsServerError() bool {
	return false
}

// IsCode returns true when this pipeline service upload pipeline o k response a status code equal to that given
func (o *PipelineServiceUploadPipelineOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the pipeline service upload pipeline o k response
func (o *PipelineServiceUploadPipelineOK) Code() int {
	return 200
}

func (o *PipelineServiceUploadPipelineOK) Error() string {
	return fmt.Sprintf("[POST /apis/v1/pipelines/upload][%d] pipelineServiceUploadPipelineOK  %+v", 200, o.Payload)
}

func (o *PipelineServiceUploadPipelineOK) String() string {
	return fmt.Sprintf("[POST /apis/v1/pipelines/upload][%d] pipelineServiceUploadPipelineOK  %+v", 200, o.Payload)
}

func (o *PipelineServiceUploadPipelineOK) GetPayload() *pipeline_upload_model.V1Pipeline {
	return o.Payload
}

func (o *PipelineServiceUploadPipelineOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(pipeline_upload_model.V1Pipeline)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPipelineServiceUploadPipelineDefault creates a PipelineServiceUploadPipelineDefault with default headers values
func NewPipelineServiceUploadPipelineDefault(code int) *PipelineServiceUploadPipelineDefault {
	return &PipelineServiceUploadPipelineDefault{
		_statusCode: code,
	}
}

/*
PipelineServiceUploadPipelineDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type PipelineServiceUploadPipelineDefault struct {
	_statusCode int

	Payload *pipeline_upload_model.GooglerpcStatus
}

// IsSuccess returns true when this pipeline service upload pipeline default response has a 2xx status code
func (o *PipelineServiceUploadPipelineDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this pipeline service upload pipeline default response has a 3xx status code
func (o *PipelineServiceUploadPipelineDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this pipeline service upload pipeline default response has a 4xx status code
func (o *PipelineServiceUploadPipelineDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this pipeline service upload pipeline default response has a 5xx status code
func (o *PipelineServiceUploadPipelineDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this pipeline service upload pipeline default response a status code equal to that given
func (o *PipelineServiceUploadPipelineDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the pipeline service upload pipeline default response
func (o *PipelineServiceUploadPipelineDefault) Code() int {
	return o._statusCode
}

func (o *PipelineServiceUploadPipelineDefault) Error() string {
	return fmt.Sprintf("[POST /apis/v1/pipelines/upload][%d] PipelineService_UploadPipeline default  %+v", o._statusCode, o.Payload)
}

func (o *PipelineServiceUploadPipelineDefault) String() string {
	return fmt.Sprintf("[POST /apis/v1/pipelines/upload][%d] PipelineService_UploadPipeline default  %+v", o._statusCode, o.Payload)
}

func (o *PipelineServiceUploadPipelineDefault) GetPayload() *pipeline_upload_model.GooglerpcStatus {
	return o.Payload
}

func (o *PipelineServiceUploadPipelineDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(pipeline_upload_model.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
