// Code generated by go-swagger; DO NOT EDIT.

package pipeline_upload_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPipelineServiceUploadPipelineParams creates a new PipelineServiceUploadPipelineParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPipelineServiceUploadPipelineParams() *PipelineServiceUploadPipelineParams {
	return &PipelineServiceUploadPipelineParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPipelineServiceUploadPipelineParamsWithTimeout creates a new PipelineServiceUploadPipelineParams object
// with the ability to set a timeout on a request.
func NewPipelineServiceUploadPipelineParamsWithTimeout(timeout time.Duration) *PipelineServiceUploadPipelineParams {
	return &PipelineServiceUploadPipelineParams{
		timeout: timeout,
	}
}

// NewPipelineServiceUploadPipelineParamsWithContext creates a new PipelineServiceUploadPipelineParams object
// with the ability to set a context for a request.
func NewPipelineServiceUploadPipelineParamsWithContext(ctx context.Context) *PipelineServiceUploadPipelineParams {
	return &PipelineServiceUploadPipelineParams{
		Context: ctx,
	}
}

// NewPipelineServiceUploadPipelineParamsWithHTTPClient creates a new PipelineServiceUploadPipelineParams object
// with the ability to set a custom HTTPClient for a request.
func NewPipelineServiceUploadPipelineParamsWithHTTPClient(client *http.Client) *PipelineServiceUploadPipelineParams {
	return &PipelineServiceUploadPipelineParams{
		HTTPClient: client,
	}
}

/*
PipelineServiceUploadPipelineParams contains all the parameters to send to the API endpoint

	for the pipeline service upload pipeline operation.

	Typically these are written to a http.Request.
*/
type PipelineServiceUploadPipelineParams struct {

	// Description.
	Description *string

	// Name.
	Name *string

	/* Uploadfile.

	   The pipeline to upload. Maximum size of 32MB is supported.
	*/
	Uploadfile runtime.NamedReadCloser

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the pipeline service upload pipeline params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PipelineServiceUploadPipelineParams) WithDefaults() *PipelineServiceUploadPipelineParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the pipeline service upload pipeline params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PipelineServiceUploadPipelineParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the pipeline service upload pipeline params
func (o *PipelineServiceUploadPipelineParams) WithTimeout(timeout time.Duration) *PipelineServiceUploadPipelineParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the pipeline service upload pipeline params
func (o *PipelineServiceUploadPipelineParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the pipeline service upload pipeline params
func (o *PipelineServiceUploadPipelineParams) WithContext(ctx context.Context) *PipelineServiceUploadPipelineParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the pipeline service upload pipeline params
func (o *PipelineServiceUploadPipelineParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the pipeline service upload pipeline params
func (o *PipelineServiceUploadPipelineParams) WithHTTPClient(client *http.Client) *PipelineServiceUploadPipelineParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the pipeline service upload pipeline params
func (o *PipelineServiceUploadPipelineParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDescription adds the description to the pipeline service upload pipeline params
func (o *PipelineServiceUploadPipelineParams) WithDescription(description *string) *PipelineServiceUploadPipelineParams {
	o.SetDescription(description)
	return o
}

// SetDescription adds the description to the pipeline service upload pipeline params
func (o *PipelineServiceUploadPipelineParams) SetDescription(description *string) {
	o.Description = description
}

// WithName adds the name to the pipeline service upload pipeline params
func (o *PipelineServiceUploadPipelineParams) WithName(name *string) *PipelineServiceUploadPipelineParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the pipeline service upload pipeline params
func (o *PipelineServiceUploadPipelineParams) SetName(name *string) {
	o.Name = name
}

// WithUploadfile adds the uploadfile to the pipeline service upload pipeline params
func (o *PipelineServiceUploadPipelineParams) WithUploadfile(uploadfile runtime.NamedReadCloser) *PipelineServiceUploadPipelineParams {
	o.SetUploadfile(uploadfile)
	return o
}

// SetUploadfile adds the uploadfile to the pipeline service upload pipeline params
func (o *PipelineServiceUploadPipelineParams) SetUploadfile(uploadfile runtime.NamedReadCloser) {
	o.Uploadfile = uploadfile
}

// WriteToRequest writes these params to a swagger request
func (o *PipelineServiceUploadPipelineParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Description != nil {

		// query param description
		var qrDescription string

		if o.Description != nil {
			qrDescription = *o.Description
		}
		qDescription := qrDescription
		if qDescription != "" {

			if err := r.SetQueryParam("description", qDescription); err != nil {
				return err
			}
		}
	}

	if o.Name != nil {

		// query param name
		var qrName string

		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {

			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}
	}
	// form file param uploadfile
	if err := r.SetFileParam("uploadfile", o.Uploadfile); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
