// Code generated by go-swagger; DO NOT EDIT.

package pipeline_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1URL v1 Url
//
// swagger:model v1Url
type V1URL struct {

	// URL of the pipeline definition or the pipeline version definition.
	PipelineURL string `json:"pipelineUrl,omitempty"`
}

// Validate validates this v1 Url
func (m *V1URL) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 Url based on context it is used
func (m *V1URL) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1URL) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1URL) UnmarshalBinary(b []byte) error {
	var res V1URL
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
