apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: template
spec:
  params:
    - name: repository
      description: The git repo
    - name: revision
      description: the branch for the git repo
    - name: apikey
      description: the ibmcloud api key
    - name: registry-url
      description: ibm container registry url
    - name: registry-namespace
      description: the ibmcloud registry namespace
    - name: region
      description: the ibmcloud registry region
      default: us-south
    - name: org
      description: organization
    - name: space
      description: space
      default: dev
    - name: resource-group
      description: resource group
      default: default
    - name: docker-username
      description: ibm container registry username
      default: iamapikey
    - name: docker-password
      description: iam api key
    - name: public-cr-username
      description: username for docker hub
    - name: public-cr-password
      description: password/token for public container registry
    - name: public-cr
      description: public container registry
      default: docker.io
    - name: tekton-version
      description: tekton version
    - name: tekton-ns
      description: tekton namespace
      default: tekton-pipeline
    - name: kubernetes-cluster
      description: cluster name
    - name: kubeflow-ns
      description: kubeflow namespace
      default: kubeflow
    - name: slack-webhook
      description: webhook URL
      default: ""
    - name: slack-channel
      description: slack channel
      default: ""
    - name: publish-to-public-cr
      description: publish images to public container registry
      default: "0"
    - name: extra-test-cases
      description: run extra test cases
      default: "0"
    - name: skip-pipeline-loop
      descript: skip the pipeline loop test case
      default: "0"
    - name: image-tag
      description: image tag
      default: "nightly"
    - name: public-cr-namespace
      description: namespace for public container registry
      default: aipipeline
    - name: images
      description: a image list for publishing
      default: "api-server persistenceagent metadata-writer scheduledworkflow cache-server frontend pipelineloop-controller pipelineloop-webhook kubeclient"
    - name: many-edge-duration
      description: duration threshold for many edge pipeline
      value: "7"
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
            name: pipeline
        workspaces:
          - name: pipeline-pvc
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
        params:
        - name: repository
          value: $(params.repository)
        - name: revision
          value: $(params.revision)
        - name: apikey
          value: $(params.apikey)
        - name: registry-url
          value: $(params.registry-url)
        - name: registry-namespace
          value: $(params.registry-namespace)
        - name: region
          value: $(params.region)
        - name: docker-username
          value: $(params.docker-username)
        - name: docker-password
          value: $(params.docker-password)
        - name: public-cr-username
          value: $(params.public-cr-username)
        - name: public-cr-password
          value: $(params.public-cr-password)
        - name: resource-group
          value: $(params.resource-group)
        - name: org
          value: $(params.org)
        - name: space
          value: $(params.space)
        - name: tekton-version
          value: $(params.tekton-version)
        - name: tekton-ns
          value: $(params.tekton-ns)
        - name: kubernetes-cluster
          value: $(params.kubernetes-cluster)
        - name: kubeflow-ns
          value: $(params.kubeflow-ns)
        - name: slack-webhook
          value: $(params.slack-webhook)
        - name: slack-channel
          value: $(params.slack-channel)
        - name: image-tag
          value: $(params.image-tag)
        - name: public-cr
          value: $(params.public-cr)
        - name: public-cr-namespace
          value: $(params.public-cr-namespace)
        - name: publish-to-public-cr
          value: $(params.publish-to-public-cr)
        - name: extra-test-cases
          value: $(params.extra-test-cases)
        - name: skip-pipeline-loop
          value: $(params.skip-pipeline-loop)
        - name: images
          value: $(params.images)
        - name: many-edge-duration
          value: $(params.many-edge-duration)
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: binding
spec:
  params:
    - name: repository
      value: "https://github.com/kubeflow/kfp-tekton"
    - name: revision
      value: "master"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: listener
spec:
  triggers:
    - binding:
        name: binding
      template:
        name: template
