// Code generated by go-swagger; DO NOT EDIT.

package run_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// V1RunStorageState v1 run storage state
// swagger:model v1RunStorageState
type V1RunStorageState string

const (

	// V1RunStorageStateSTORAGESTATEAVAILABLE captures enum value "STORAGESTATE_AVAILABLE"
	V1RunStorageStateSTORAGESTATEAVAILABLE V1RunStorageState = "STORAGESTATE_AVAILABLE"

	// V1RunStorageStateSTORAGESTATEARCHIVED captures enum value "STORAGESTATE_ARCHIVED"
	V1RunStorageStateSTORAGESTATEARCHIVED V1RunStorageState = "STORAGESTATE_ARCHIVED"
)

// for schema
var v1RunStorageStateEnum []interface{}

func init() {
	var res []V1RunStorageState
	if err := json.Unmarshal([]byte(`["STORAGESTATE_AVAILABLE","STORAGESTATE_ARCHIVED"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		v1RunStorageStateEnum = append(v1RunStorageStateEnum, v)
	}
}

func (m V1RunStorageState) validateV1RunStorageStateEnum(path, location string, value V1RunStorageState) error {
	if err := validate.Enum(path, location, value, v1RunStorageStateEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this v1 run storage state
func (m V1RunStorageState) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateV1RunStorageStateEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
