// Code generated by go-swagger; DO NOT EDIT.

package run_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1ReadArtifactResponse v1 read artifact response
//
// swagger:model v1ReadArtifactResponse
type V1ReadArtifactResponse struct {

	// The bytes of the artifact content.
	// Format: byte
	Data strfmt.Base64 `json:"data,omitempty"`
}

// Validate validates this v1 read artifact response
func (m *V1ReadArtifactResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 read artifact response based on context it is used
func (m *V1ReadArtifactResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1ReadArtifactResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1ReadArtifactResponse) UnmarshalBinary(b []byte) error {
	var res V1ReadArtifactResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
