// Code generated by go-swagger; DO NOT EDIT.

package run_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1Value Value is the value of the field.
//
// swagger:model v1Value
type V1Value struct {

	// A double value
	DoubleValue float64 `json:"doubleValue,omitempty"`

	// An integer value
	IntValue string `json:"intValue,omitempty"`

	// A string value
	StringValue string `json:"stringValue,omitempty"`
}

// Validate validates this v1 value
func (m *V1Value) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 value based on context it is used
func (m *V1Value) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1Value) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1Value) UnmarshalBinary(b []byte) error {
	var res V1Value
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
