// Copyright 2023 kubeflow.org
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kubeflow/kfp-tekton/tekton-catalog/tekton-exithandler/pkg/apis/exithandler/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ExitHandlerLister helps list ExitHandlers.
// All objects returned here must be treated as read-only.
type ExitHandlerLister interface {
	// List lists all ExitHandlers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ExitHandler, err error)
	// ExitHandlers returns an object that can list and get ExitHandlers.
	ExitHandlers(namespace string) ExitHandlerNamespaceLister
	ExitHandlerListerExpansion
}

// exitHandlerLister implements the ExitHandlerLister interface.
type exitHandlerLister struct {
	indexer cache.Indexer
}

// NewExitHandlerLister returns a new ExitHandlerLister.
func NewExitHandlerLister(indexer cache.Indexer) ExitHandlerLister {
	return &exitHandlerLister{indexer: indexer}
}

// List lists all ExitHandlers in the indexer.
func (s *exitHandlerLister) List(selector labels.Selector) (ret []*v1alpha1.ExitHandler, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ExitHandler))
	})
	return ret, err
}

// ExitHandlers returns an object that can list and get ExitHandlers.
func (s *exitHandlerLister) ExitHandlers(namespace string) ExitHandlerNamespaceLister {
	return exitHandlerNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// ExitHandlerNamespaceLister helps list and get ExitHandlers.
// All objects returned here must be treated as read-only.
type ExitHandlerNamespaceLister interface {
	// List lists all ExitHandlers in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ExitHandler, err error)
	// Get retrieves the ExitHandler from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.ExitHandler, error)
	ExitHandlerNamespaceListerExpansion
}

// exitHandlerNamespaceLister implements the ExitHandlerNamespaceLister
// interface.
type exitHandlerNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all ExitHandlers in the indexer for a given namespace.
func (s exitHandlerNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.ExitHandler, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ExitHandler))
	})
	return ret, err
}

// Get retrieves the ExitHandler from the indexer for a given namespace and name.
func (s exitHandlerNamespaceLister) Get(name string) (*v1alpha1.ExitHandler, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("exithandler"), name)
	}
	return obj.(*v1alpha1.ExitHandler), nil
}
