---
apiVersion: v1
kind: Service
metadata:
  name: filebrowser
  namespace: kubeflow
  labels:
    app: filebrowser
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: filebrowser
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  namespace: kubeflow
  labels:
    app: filebrowser
spec:
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      containers:
        - image: filebrowser/filebrowser:latest
          name: filebrowser
          ports:
            - containerPort: 80
              name: filebrowser
          volumeMounts:
            - name: tfx-volume
              mountPath: /srv
      volumes:
        - name: tfx-volume
          persistentVolumeClaim:
            claimName: tfx-volume
