apiVersion: custom.tekton.dev/v1alpha1
kind: PipelineLoop
metadata:
  name: echoloop
spec:
  pipelineSpec:
    params:
    - name: message-subvar-a
      type: string
    - name: message-subvar-b
      type: string
    tasks:
    - name: echo-good-morning
      params:
      - name: message-subvar-a
        value: $(params.message-subvar-a)
      - name: message-subvar-b
        value: $(params.message-subvar-b)
      taskSpec:
        params:
        - name: message-subvar-a
          type: string
        - name: message-subvar-b
          type: string
        steps:
          - name: echo
            image: ubuntu
            imagePullPolicy: IfNotPresent
            script: |
              #!/usr/bin/env bash
              echo "subvar-a: $(params.message-subvar-a)"
              echo "subvar-b: $(params.message-subvar-b)"
  iterateParam: message

---
apiVersion: tekton.dev/v1alpha1
kind: Run
metadata:
  name: simplepipelinelooprun
spec:
  params:
    - name: message
      value: '[{"a":"1", "b":"2"}, {"a":"2", "b":"1"}]'
  ref:
    apiVersion: custom.tekton.dev/v1alpha1
    kind: PipelineLoop
    name: echoloop

