apiVersion: custom.tekton.dev/v1alpha1
kind: PipelineLoop
metadata:
  name: pipelineloop
spec:
  pipelineSpec:
    params:
    - name: message
      type: string
    tasks:
    - name: echo-loop-task
      params:
      - name: message
        value: $(params.message)
      taskSpec:
        params:
        - name: message
          type: string
        steps:
          - name: echo
            image: ubuntu
            imagePullPolicy: IfNotPresent
            script: |
              #!/usr/bin/env bash
              echo "$(params.message)"
  iterateParam: message

---

apiVersion: tekton.dev/v1alpha1
kind: Run
metadata:
  labels:
    custom.tekton.dev/pipelineLoop: pipelineloop
    tekton.dev/pipeline: pr-loop-example
    tekton.dev/pipelineRun: pr-loop-example
    tekton.dev/pipelineTask: loop-task
  name: pr-loop-example-loop-9w87k
spec:
  params:
  - name: message
    value:
    - I am the first one
    - I am the second one
    - I am the third one
  ref:
    apiVersion: custom.tekton.dev/v1alpha1
    kind: PipelineLoop
    name: pipelineloop
