apiVersion: custom.tekton.dev/v1alpha1
kind: PipelineLoop
metadata:
  name: echoloop
spec:
  pipelineSpec:
    params:
    - name: iteration-item
      type: string
    tasks:
    - name: echo-good-morning
      params:
      - name: iteration-item
        value: $(params.iteration-item)
      taskSpec:
        params:
        - name: iteration-item
          type: string
        steps:
          - name: echo
            image: ubuntu
            imagePullPolicy: IfNotPresent
            script: |
              #!/usr/bin/env bash
              echo "$(params.iteration-item)"
  iterateNumeric: iteration-item

---
apiVersion: tekton.dev/v1beta1
kind: CustomRun
metadata:
  name: simplepipelinelooprun
spec:
  params:
    - name: from
      value: '10'
    - name: step
      value: '1'
    - name: to
      value: '15'
  customRef:
    apiVersion: custom.tekton.dev/v1alpha1
    kind: PipelineLoop
    name: echoloop

