apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pr-loop-example
  labels:
    mylooplabels: mylooplabels
spec:
  pipelineSpec:
    tasks:
      - name: first-task
        taskSpec:
          steps:
            - name: echo
              image: ubuntu
              imagePullPolicy: IfNotPresent
              script: |
                #!/usr/bin/env bash
                echo "I am the first task before the loop task"
      - name: loop-task
        runAfter:
          - first-task
        params:
          - name: message
            value:
              - I am the first one
              - I am the second one
              - I am the third one
        taskSpec:
          apiVersion: custom.tekton.dev/v1alpha1
          kind: PipelineLoop
          spec:
            iterateParam: message
            pipelineSpec:
              params:
                - name: message
                  type: string
              tasks:
                - name: echo-loop-task
                  params:
                    - name: message
                      value: $(params.message)
                  taskSpec:
                    params:
                      - name: message
                        type: string
                    steps:
                      - name: echo
                        image: ubuntu
                        imagePullPolicy: IfNotPresent
                        script: |
                          #!/usr/bin/env bash
                          echo "$(params.message)"
                - name: loop-task-inner
                  runAfter:
                    - echo-loop-task
                  params:
                    - name: message
                      value:
                        - I am the inner first one
                        - I am the inner second one
                  taskSpec:
                    apiVersion: custom.tekton.dev/v1alpha1
                    kind: PipelineLoop
                    spec:
                      iterateParam: message
                      pipelineSpec:
                        params:
                          - name: message
                            type: string
                        tasks:
                          - name: echo-loop-task
                            params:
                              - name: message
                                value: $(params.message)
                            taskSpec:
                              params:
                                - name: message
                                  type: string
                              steps:
                                - name: echo
                                  image: ubuntu
                                  imagePullPolicy: IfNotPresent
                                  script: |
                                    #!/usr/bin/env bash
                                    echo "$(params.message)"
      - name: last-task
        runAfter:
          - loop-task
        taskSpec:
          steps:
            - name: echo
              image: ubuntu
              imagePullPolicy: IfNotPresent
              script: |
                #!/usr/bin/env bash
                echo "I am the last task after the loop task"
