apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: simpletask2
spec:
  params:
    - name: word
      type: string
    - name: suffix
      type: string
  steps:
    - name: echo
      image: ubuntu
      script: |
        #!/usr/bin/env bash
        echo "$(params.word)$(params.suffix)"
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: demo-pipeline1
spec:
  params:
  - name: word
    default: "wordi"
  - name: suffix
    default: "suffixi"
  tasks:
  - name: simplepipelinetask
    taskRef:
      name: simpletask2
    params:
    - name: word
      value: $(params.word)
    - name: suffix
      value: $(params.suffix)
---
apiVersion: tekton.dev/v1alpha1
kind: Run
metadata:
  name: simpletasklooprun02
spec:
  params:
    - name: word
      value:
        - jump0
        - land0
        - roll0
    - name: suffix
      value: ing
  spec:
    apiVersion: custom.tekton.dev/v1alpha1
    kind: PipelineLoop
    spec:
      pipelineRef:
        name: demo-pipeline1
      iterateParam: word
      timeout: 60s
