# coding: utf-8

"""
    Kubeflow Pipelines API

    This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.

    Contact: kubeflow-pipelines@google.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import kfp_tekton_server_api
from kfp_tekton_server_api.api.run_service_api import RunServiceApi  # noqa: E501
from kfp_tekton_server_api.rest import ApiException


class TestRunServiceApi(unittest.TestCase):
    """RunServiceApi unit test stubs"""

    def setUp(self):
        self.api = kfp_tekton_server_api.api.run_service_api.RunServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_run_service_archive_run(self):
        """Test case for run_service_archive_run

        Archives a run.  # noqa: E501
        """
        pass

    def test_run_service_create_run(self):
        """Test case for run_service_create_run

        Creates a new run.  # noqa: E501
        """
        pass

    def test_run_service_delete_run(self):
        """Test case for run_service_delete_run

        Deletes a run.  # noqa: E501
        """
        pass

    def test_run_service_get_run(self):
        """Test case for run_service_get_run

        Finds a specific run by ID.  # noqa: E501
        """
        pass

    def test_run_service_list_runs(self):
        """Test case for run_service_list_runs

        Finds all runs.  # noqa: E501
        """
        pass

    def test_run_service_read_artifact(self):
        """Test case for run_service_read_artifact

        Finds a run's artifact data.  # noqa: E501
        """
        pass

    def test_run_service_report_run_metrics(self):
        """Test case for run_service_report_run_metrics

        ReportRunMetrics reports metrics of a run. Each metric is reported in its own transaction, so this API accepts partial failures. Metric can be uniquely identified by (run_id, node_id, name). Duplicate reporting will be ignored by the API. First reporting wins.  # noqa: E501
        """
        pass

    def test_run_service_retry_run(self):
        """Test case for run_service_retry_run

        Re-initiates a failed or terminated run.  # noqa: E501
        """
        pass

    def test_run_service_terminate_run(self):
        """Test case for run_service_terminate_run

        Terminates an active run.  # noqa: E501
        """
        pass

    def test_run_service_unarchive_run(self):
        """Test case for run_service_unarchive_run

        Restores an archived run.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
