# coding: utf-8

"""
    Kubeflow Pipelines API

    This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.

    Contact: kubeflow-pipelines@google.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import kfp_tekton_server_api
from kfp_tekton_server_api.models.v1_run_metric import V1RunMetric  # noqa: E501
from kfp_tekton_server_api.rest import ApiException

class TestV1RunMetric(unittest.TestCase):
    """V1RunMetric unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1RunMetric
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = kfp_tekton_server_api.models.v1_run_metric.V1RunMetric()  # noqa: E501
        if include_optional :
            return V1RunMetric(
                name = '0', 
                node_id = '0', 
                number_value = 1.337, 
                format = 'UNSPECIFIED'
            )
        else :
            return V1RunMetric(
        )

    def testV1RunMetric(self):
        """Test V1RunMetric"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
