// Copyright 2023 kubeflow.org
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/kubeflow/pipelines/backend/src/v2/tekton-kfptask/apis/kfptask/v1alpha1"
	scheme "github.com/kubeflow/pipelines/backend/src/v2/tekton-kfptask/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// KfpTasksGetter has a method to return a KfpTaskInterface.
// A group's client should implement this interface.
type KfpTasksGetter interface {
	KfpTasks(namespace string) KfpTaskInterface
}

// KfpTaskInterface has methods to work with KfpTask resources.
type KfpTaskInterface interface {
	Create(ctx context.Context, kfpTask *v1alpha1.KfpTask, opts v1.CreateOptions) (*v1alpha1.KfpTask, error)
	Update(ctx context.Context, kfpTask *v1alpha1.KfpTask, opts v1.UpdateOptions) (*v1alpha1.KfpTask, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.KfpTask, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.KfpTaskList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KfpTask, err error)
	KfpTaskExpansion
}

// kfpTasks implements KfpTaskInterface
type kfpTasks struct {
	client rest.Interface
	ns     string
}

// newKfpTasks returns a KfpTasks
func newKfpTasks(c *CustomV1alpha1Client, namespace string) *kfpTasks {
	return &kfpTasks{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the kfpTask, and returns the corresponding kfpTask object, and an error if there is any.
func (c *kfpTasks) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.KfpTask, err error) {
	result = &v1alpha1.KfpTask{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kfptasks").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of KfpTasks that match those selectors.
func (c *kfpTasks) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KfpTaskList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.KfpTaskList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kfptasks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested kfpTasks.
func (c *kfpTasks) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("kfptasks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a kfpTask and creates it.  Returns the server's representation of the kfpTask, and an error, if there is any.
func (c *kfpTasks) Create(ctx context.Context, kfpTask *v1alpha1.KfpTask, opts v1.CreateOptions) (result *v1alpha1.KfpTask, err error) {
	result = &v1alpha1.KfpTask{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("kfptasks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kfpTask).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a kfpTask and updates it. Returns the server's representation of the kfpTask, and an error, if there is any.
func (c *kfpTasks) Update(ctx context.Context, kfpTask *v1alpha1.KfpTask, opts v1.UpdateOptions) (result *v1alpha1.KfpTask, err error) {
	result = &v1alpha1.KfpTask{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kfptasks").
		Name(kfpTask.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kfpTask).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the kfpTask and deletes it. Returns an error if one occurs.
func (c *kfpTasks) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kfptasks").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *kfpTasks) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kfptasks").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched kfpTask.
func (c *kfpTasks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KfpTask, err error) {
	result = &v1alpha1.KfpTask{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("kfptasks").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
