name: KFP Tekton pipelineloop unit tests

on:
  push:
    branches: [v2-integration]

  # Run tests for any PRs.
  pull_request:
    paths:
      - 'tekton-catalog/pipeline-loops/go.mod'
      - 'tekton-catalog/pipeline-loops/cmd/**'
      - 'tekton-catalog/pipeline-loops/pkg/**'
      - 'tekton-catalog/pipeline-loops/test/**'

env:
  GITHUB_ACTION: "true"
  SETUPTOOLS_USE_DISTUTILS: "stdlib"

jobs:
  run-pipelineloop-unittests:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: "run go pipelineLoop unit tests"
        run: cd tekton-catalog/pipeline-loops && make test-all
